//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVRES
    {
        public int ID_LIVRE { get; set; }
        public Nullable<decimal> ISBN { get; set; }
        public string TITRE { get; set; }
        public string EDITEUR { get; set; }
        public Nullable<System.DateTime> ANNEE_EDITION { get; set; }
        public Nullable<int> ID_AUTEUR { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
        public string LIVRE { get; set; }
        public string URL_LIVRE { get; set; }
    
        public virtual AUTEURS AUTEURS { get; set; }
        public virtual GENRES GENRES { get; set; }
    }
}
